package com.zed.model;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_table.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_table.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_table.password
     *
     * @mbg.generated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_table.gender
     *
     * @mbg.generated
     */
    private String gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_table.hobby
     *
     * @mbg.generated
     */
    private String hobby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_table.regDate
     *
     * @mbg.generated
     */
    private String regdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_table.avatar
     *
     * @mbg.generated
     */
    private String avatar;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_table.homeAddress
     *
     * @mbg.generated
     */
    private String homeaddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_table.workAddress
     *
     * @mbg.generated
     */
    private String workaddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_table.userInfo
     *
     * @mbg.generated
     */
    private byte[] userinfo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_table.id
     *
     * @return the value of user_table.id
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_table.id
     *
     * @param id the value for user_table.id
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_table.name
     *
     * @return the value of user_table.name
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_table.name
     *
     * @param name the value for user_table.name
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_table.password
     *
     * @return the value of user_table.password
     * @mbg.generated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_table.password
     *
     * @param password the value for user_table.password
     * @mbg.generated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_table.gender
     *
     * @return the value of user_table.gender
     * @mbg.generated
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_table.gender
     *
     * @param gender the value for user_table.gender
     * @mbg.generated
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_table.hobby
     *
     * @return the value of user_table.hobby
     * @mbg.generated
     */
    public String getHobby() {
        return hobby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_table.hobby
     *
     * @param hobby the value for user_table.hobby
     * @mbg.generated
     */
    public void setHobby(String hobby) {
        this.hobby = hobby == null ? null : hobby.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_table.regDate
     *
     * @return the value of user_table.regDate
     * @mbg.generated
     */
    public String getRegdate() {
        return regdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_table.regDate
     *
     * @param regdate the value for user_table.regDate
     * @mbg.generated
     */
    public void setRegdate(String regdate) {
        this.regdate = regdate == null ? null : regdate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_table.avatar
     *
     * @return the value of user_table.avatar
     * @mbg.generated
     */
    public String getAvatar() {
        return avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_table.avatar
     *
     * @param avatar the value for user_table.avatar
     * @mbg.generated
     */
    public void setAvatar(String avatar) {
        this.avatar = avatar == null ? null : avatar.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_table.homeAddress
     *
     * @return the value of user_table.homeAddress
     * @mbg.generated
     */
    public String getHomeaddress() {
        return homeaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_table.homeAddress
     *
     * @param homeaddress the value for user_table.homeAddress
     * @mbg.generated
     */
    public void setHomeaddress(String homeaddress) {
        this.homeaddress = homeaddress == null ? null : homeaddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_table.workAddress
     *
     * @return the value of user_table.workAddress
     * @mbg.generated
     */
    public String getWorkaddress() {
        return workaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_table.workAddress
     *
     * @param workaddress the value for user_table.workAddress
     * @mbg.generated
     */
    public void setWorkaddress(String workaddress) {
        this.workaddress = workaddress == null ? null : workaddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_table.userInfo
     *
     * @return the value of user_table.userInfo
     * @mbg.generated
     */
    public byte[] getUserinfo() {
        return userinfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_table.userInfo
     *
     * @param userinfo the value for user_table.userInfo
     * @mbg.generated
     */
    public void setUserinfo(byte[] userinfo) {
        this.userinfo = userinfo;
    }
}